In [22]:
k= input('Enter how many eigenvalues do you want:')
k=int(k)
from PIL import Image
from numpy import*
import numpy
import scipy
temp=asarray(Image.open('blackguy.jpg'))
temp.shape
print(temp)
black=numpy.zeros((temp.shape[0],temp.shape[1]))

for i in range(temp.shape[0]):
    for j in range(temp.shape[1]):
        a=i
        b=j
        black[a][b]=0.2125*temp[a][b][0]+0.7154*temp[a][b][1]+0.0721*temp[a][b][2]

Enter how many eigenvalues do you want:5
[[[59 59 59]
  [60 60 60]
  [61 61 61]
  ..., 
  [53 53 53]
  [53 53 53]
  [53 53 53]]

 [[53 53 53]
  [53 53 53]
  [54 54 54]
  ..., 
  [54 54 54]
  [54 54 54]
  [54 54 54]]

 [[52 52 52]
  [52 52 52]
  [53 53 53]
  ..., 
  [52 52 52]
  [52 52 52]
  [52 52 52]]

 ..., 
 [[20 20 20]
  [20 20 20]
  [20 20 20]
  ..., 
  [23 23 23]
  [22 22 22]
  [21 21 21]]

 [[20 20 20]
  [20 20 20]
  [20 20 20]
  ..., 
  [23 23 23]
  [22 22 22]
  [21 21 21]]

 [[19 19 19]
  [19 19 19]
  [19 19 19]
  ..., 
  [23 23 23]
  [22 22 22]
  [21 21 21]]]


In [23]:
from getdecom import getdecom
from terms import useterm
newblack=useterm(k,black)


[541440022.30641413, 27539802.754505973, 18652023.276477437, 10085545.000526981, 7414168.0763297733, 4091732.9813385531, 3324576.6602558433, 2684104.1747868825, 2215040.5534641831, 1955190.6493956619, 1336904.5867086255, 1170458.7297767964, 1007177.4825723009, 900627.10293261777, 839349.06342656945, 664552.84650587116, 647765.89865736163, 559269.43530397769, 514606.90825780586, 467949.29873994703, 456487.83760933479, 405843.55382075108, 383902.23757074459, 354355.22631580004, 331984.79544858821, 312905.63367932918, 303516.22616322548, 294230.16506764852, 288021.78033714974, 271594.95265510795, 265608.6255806128, 260886.4851511938, 246904.27611768752, 245108.30565712418, 222086.3528304917, 210317.62999656866, 206025.9078930004, 199148.67989470679, 190055.36827548008, 189437.84803370567, 182965.74148073565, 178207.23788183843, 175486.40868215205, 168594.22537708818, 163986.06094423885, 159297.223708868, 156990.29396155826, 156001.39623703554, 151968.04640954599, 146908.32999115108, 14517

In [24]:
for i in range(temp.shape[0]):
    for j in range(temp.shape[1]):
        a=i
        b=j
        newtemp[a][b][0]=newblack[a][b]
        newtemp[a][b][1]=newblack[a][b]
        newtemp[a][b][2]=newblack[a][b]

/usr/local/lib/python3.4/dist-packages/IPython/kernel/__main__.py:5: ComplexWarning: Casting complex values to real discards the imaginary part
/usr/local/lib/python3.4/dist-packages/IPython/kernel/__main__.py:6: ComplexWarning: Casting complex values to real discards the imaginary part
/usr/local/lib/python3.4/dist-packages/IPython/kernel/__main__.py:7: ComplexWarning: Casting complex values to real discards the imaginary part


In [25]:
img=Image.fromarray(newtemp,'RGB')
img.save("{}.jpg".format(k))