In [11]:
k= input('Enter how many eigenvalues do you want:')
k=int(k)
from PIL import Image
from numpy import*
import numpy
import scipy
temp=asarray(Image.open('mini.jpg'))
temp.shape
print(temp)
red=numpy.zeros((temp.shape[0],temp.shape[1]))
green=numpy.zeros((temp.shape[0],temp.shape[1]))
blue=numpy.zeros((temp.shape[0],temp.shape[1]))
for i in range(temp.shape[0]):
    for j in range(temp.shape[1]):
        a=i
        b=j
        red[a][b]=temp[a][b][0]
        green[a][b]=temp[a][b][1]
        blue[a][b]=temp[a][b][2]

Enter how many eigenvalues do you want:100
[[[  1  27  44]
  [  1  26  46]
  [  1  26  46]
  ..., 
  [ 46  95 138]
  [ 46  95 138]
  [ 46  95 138]]

 [[  1  27  44]
  [  1  27  44]
  [  1  26  46]
  ..., 
  [ 46  95 138]
  [ 46  95 138]
  [ 46  95 138]]

 [[  3  26  42]
  [  3  26  42]
  [  1  27  44]
  ..., 
  [ 46  95 138]
  [ 46  95 138]
  [ 46  95 138]]

 ..., 
 [[ 68  78 103]
  [ 70  77 103]
  [ 70  77 103]
  ..., 
  [117 153 185]
  [117 153 185]
  [116 152 184]]

 [[ 70  77 103]
  [ 70  77 103]
  [ 69  76 102]
  ..., 
  [115 149 184]
  [116 150 185]
  [117 151 186]]

 [[ 71  78 104]
  [ 70  77 103]
  [ 69  76 102]
  ..., 
  [115 149 184]
  [116 150 185]
  [117 151 186]]]


In [12]:
from getdecom import getdecom
from terms import useterm
newred=useterm(k,red)
newgreen=useterm(k,green)
newblue=useterm(k,blue)

[1229974995.5025167, 207775359.79837918, 89874881.728145823, 71766944.717364773, 38100600.296610832, 31037400.093298599, 22389286.022662882, 17668387.330940079, 12302501.7508526, 10845488.329187745, 8196613.0061256476, 7258348.9648922691, 5718620.8737891139, 4817822.7261246406, 3923341.7080041007, 3607103.5687245228, 3374604.672633491, 3111344.8404456074, 2834128.7972607752, 2414108.4517381294, 2300906.1246830523, 2239447.1404264406, 1894795.2656699196, 1656112.0103434944, 1552885.7783075511, 1393115.808058002, 1339791.5780910959, 1252539.4588116065, 1057674.5422346708, 1010050.6967554798, 967355.32905510615, 909002.62046153797, 864746.04960868752, 847619.62923082139, 788836.12457834184, 737860.5386319753, 662218.30020758673, 648172.78135636635, 615656.56434164289, 567912.40432869596, 551324.06602954143, 516691.84611265094, 508458.09505579033, 461210.74258012901, 459254.92138423282, 454156.12265187228, 434055.50542607717, 413242.04519368679, 404056.03032149735, 385123.03377785668, 3617

In [13]:
newtemp=numpy.zeros((temp.shape[0],temp.shape[1],temp.shape[2]),dtype=numpy.uint8)

In [14]:
for i in range(temp.shape[0]):
    for j in range(temp.shape[1]):
        a=i
        b=j
        newtemp[a][b][0]=newred[a][b]
        newtemp[a][b][1]=newgreen[a][b]
        newtemp[a][b][2]=newblue[a][b]

In [15]:
img=Image.fromarray(newtemp,'RGB')
img.save("{}.jpg".format(k))