In [16]:
k= input('Enter how many eigenvalues do you want:')
k=int(k)
from PIL import Image
from numpy import*
import numpy
import scipy
temp=asarray(Image.open('grass_PNG4930.png'))
temp.shape
print(temp)
red=numpy.zeros((temp.shape[0],temp.shape[1]))
green=numpy.zeros((temp.shape[0],temp.shape[1]))
blue=numpy.zeros((temp.shape[0],temp.shape[1]))
one=numpy.zeros((temp.shape[0],temp.shape[1]))
for i in range(temp.shape[0]):
    for j in range(temp.shape[1]):
        red[i][j]=temp[i][j][0]
        green[i][j]=temp[i][j][1]
        blue[i][j]=temp[i][j][2]
        one[i][j]=temp[i][j][3]

Enter how many eigenvalues do you want:819
[[[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  ..., 
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  ..., 
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  ..., 
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]

 ..., 
 [[ 17  64   2 255]
  [  4  34   0 255]
  [  3  32   0 255]
  ..., 
  [ 29  89   4 255]
  [ 25  90   3 255]
  [ 24  93   4 255]]

 [[ 18  65   3 255]
  [  5  34   0 255]
  [  5  31   1 255]
  ..., 
  [ 29  89   5 255]
  [ 27  89   4 255]
  [ 27  93   5 255]]

 [[ 15  69   2 255]
  [  7  39   1 255]
  [  5  30   0 255]
  ..., 
  [ 28  89   6 255]
  [ 25  92   5 255]
  [ 24  95   4 255]]]


In [17]:
from getdecom import getdecom
from terms import useterm
newred=useterm(k,red)
newgreen=useterm(k,green)
newblue=useterm(k,blue)

Eigenvalue of U:
[  2.60968877e+09   1.26358455e+08   4.08758200e+07   3.92738714e+07
   3.37102185e+07   3.28239900e+07   2.78923291e+07   2.63331958e+07
   2.29367840e+07   2.27093452e+07   2.05955848e+07   1.82578727e+07
   1.58403213e+07   1.39013609e+07   1.36582992e+07   1.28885880e+07
   1.24318287e+07   1.16227372e+07   1.14557211e+07   1.05000420e+07
   1.01219635e+07   9.92634377e+06   9.53479987e+06   9.13038391e+06
   8.61230511e+06   8.13226206e+06   7.94691688e+06   7.63220489e+06
   7.50967115e+06   7.14441374e+06   7.01454629e+06   6.65486384e+06
   6.50277185e+06   6.44868536e+06   6.24266073e+06   5.91675834e+06
   5.83265315e+06   5.77055239e+06   5.67481796e+06   5.44633226e+06
   5.25865947e+06   5.23310698e+06   4.90315723e+06   4.83544488e+06
   4.78797408e+06   4.63062848e+06   4.61141639e+06   4.50885479e+06
   4.32806902e+06   4.26240460e+06   4.20497117e+06   4.00509033e+06
   4.03297065e+06   3.89814502e+06   3.85964722e+06   3.81605395e+06
   3.75046609e+06

In [18]:
newtemp=numpy.zeros((temp.shape[0],temp.shape[1],temp.shape[2]),dtype=numpy.uint8)

In [19]:
for i in range(temp.shape[0]):
    for j in range(temp.shape[1]):
        newtemp[i][j][0]=newred[i][j]
        newtemp[i][j][1]=newgreen[i][j]
        newtemp[i][j][2]=newblue[i][j]
        newtemp[i][j][3]=one[i][j]

In [20]:
img=Image.fromarray(newtemp,'RGBA')
img.save("{}.png".format(k))

<img src=""{}.png".format(k)">